# Flujo de trabajo GitHub Actions

name: CI

# Control de ejecución
on:
  # Activa el flujo de trabajo en eventos de solicitud de push o pull request, pero solo para la rama master
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo.
jobs:
  # Este flujo de trabajo contiene un único trabajo llamado "compilación".
  build:
    # El tipo de runner en el que se ejecutará el job.
    runs-on: ubuntu-latest

    # Los steps representan una secuencia de tareas que se ejecutarán como parte del job.
    steps:
      # Registra el repositorio en $GITHUB_WORKSPACE, para que el job pueda acceder a él.
      - uses: actions/checkout@v2

      # Ejecuta un solo comando usando el shell de runners
      - name: Ejecutar un script de una línea
        run: echo Hello, world!

      # Ejecuta un conjunto de comandos usando el shell de los runners.
      - name: Ejecute un script de varias línea
        run: |
          echo Agregando otras acciones para construir,
          echo Test e implementación del código.
      - name: Despliegue de aplicación angular en GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          # Github access token, token que se usa para implementar en github_pages. (Se configura en secrets de GitHub)
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          # El directorio del proyecto angular, en el que se ejecutarán todos los comandos.
          #angular_project_dir: # optional, default es ./
          # Configuración para la aplicación angular - dev-qa-prod
          # optional, default is dev
          #build_configuration: dev
          # base href para la aplicación
          # optional, defecto is /
          # Un ejemplo de que esto corresponda a https://<your_username>.github.io/<base_href>/
          base_href: /votos-angular-ci-cd/
          # rama en la que se implementará la construcción angular
          # optional, defecto is gh-pages
          deploy_branch: master
          # La carpeta en la que `ng build` proporciona su salida. Esta es la carpeta que se implementará en `deploy_branch`.
          # optional, defecto es dist
          angular_dist_build_folder: dist/angular-links-vote-app
          # Aplicar la acción debe ejecutar 'ng lint'
          #run_lint: # optional
          # No fallará el step si algo falla
          #skip_failure: # optional
