# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Angular Deploy gh-pages Actions
        # You may pin to the exact commit or the version.
        # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          # Github access token token used to deploy on gh_pages. You can find it on Github.
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          # The directory of the angular project, in which all the commands will run
          #angular_project_dir: # optional, default is ./
          # Build configuration for the angular app
          # optional, default is production
          #build_configuration: production
          # base href for the app
          # optional, default is /
          # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          #base_href: /venta-empresa/
          # branch on which the angular build will be deployed
          # optional, default is gh-pages
          deploy_branch: master
          # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
          # optional, default is dist
          angular_dist_build_folder: dist/angular-links-vote-app
          # If the action should run 'ng lint'
          #run_lint: # optional
          # Will not fail the step if anything fails
          #skip_failure: # optional
